"""added pronoun table

Revision ID: 03472eaee977
Revises: 1781c5317e42
Create Date: 2020-10-29 17:13:27.584085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03472eaee977'
down_revision = '1781c5317e42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pronouns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pronoun', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('pronoun_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'pronouns', ['pronoun_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'pronoun_id')
    op.drop_table('pronouns')
    # ### end Alembic commands ###
