"""changed mc_question mc_answer_options relationship

Revision ID: fa4f050092c2
Revises: ed279c8fd64e
Create Date: 2020-10-25 20:34:57.122303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa4f050092c2'
down_revision = 'ed279c8fd64e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mc_answer_options', sa.Column('mc_question_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'mc_answer_options', 'mc_questions', ['mc_question_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mc_answer_options', type_='foreignkey')
    op.drop_column('mc_answer_options', 'mc_question_id')
    # ### end Alembic commands ###
