"""rejects

Revision ID: 4331bcb165b4
Revises: fd9764f8b927
Create Date: 2020-10-30 15:06:51.559380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4331bcb165b4'
down_revision = 'fd9764f8b927'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_rejects')
    op.add_column('rejects', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'rejects', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rejects', type_='foreignkey')
    op.drop_column('rejects', 'user_id')
    op.create_table('user_rejects',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reject_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['reject_id'], ['rejects.id'], name='user_rejects_reject_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_rejects_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'reject_id', name='user_rejects_pkey')
    )
    # ### end Alembic commands ###
