"""reject model

Revision ID: fd9764f8b927
Revises: 6ca6d53d27a9
Create Date: 2020-10-30 14:56:40.385744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd9764f8b927'
down_revision = '6ca6d53d27a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rejects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reject_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_rejects',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reject_id'], ['rejects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'reject_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_rejects')
    op.drop_table('rejects')
    # ### end Alembic commands ###
