"""more explicit fr and mc models

Revision ID: 7fd16fd1d860
Revises: 8d5345d189a6
Create Date: 2020-10-26 14:57:14.263655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fd16fd1d860'
down_revision = '8d5345d189a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fr_questions', sa.Column('fr_question', sa.Text(), nullable=False))
    op.drop_column('fr_questions', 'question')
    op.add_column('fr_responses', sa.Column('fr_answer', sa.Text(), nullable=False))
    op.drop_column('fr_responses', 'answer')
    op.add_column('mc_answer_options', sa.Column('mc_answer', sa.Text(), nullable=False))
    op.drop_column('mc_answer_options', 'answer')
    op.add_column('mc_questions', sa.Column('mc_question', sa.Text(), nullable=False))
    op.drop_column('mc_questions', 'question')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mc_questions', sa.Column('question', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('mc_questions', 'mc_question')
    op.add_column('mc_answer_options', sa.Column('answer', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('mc_answer_options', 'mc_answer')
    op.add_column('fr_responses', sa.Column('answer', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('fr_responses', 'fr_answer')
    op.add_column('fr_questions', sa.Column('question', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('fr_questions', 'fr_question')
    # ### end Alembic commands ###
