"""Added a password-digest field in the user table

Revision ID: ba449ee31561
Revises: fa4f050092c2
Create Date: 2020-10-27 10:43:37.374844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba449ee31561'
down_revision = 'fa4f050092c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_digest', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_digest')
    # ### end Alembic commands ###
