"""create mc tables

Revision ID: 68a1d9785243
Revises: 
Create Date: 2020-10-25 18:32:27.124093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68a1d9785243'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mc_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('mc_answer_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('mc_question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mc_question_id'], ['mc_questions.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mc_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mc_answer_option_id', sa.Integer(), nullable=False),
    sa.Column('mc_question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mc_answer_option_id'], ['mc_answer_options.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['mc_question_id'], ['mc_questions.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mc_responses')
    op.drop_table('mc_answer_options')
    op.drop_table('users')
    op.drop_table('mc_questions')
    # ### end Alembic commands ###
