"""add q_weight and unacceptable to mc_response

Revision ID: acc6a1798160
Revises: ba449ee31561
Create Date: 2020-10-28 12:00:51.916381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acc6a1798160'
down_revision = 'ba449ee31561'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mc_responses', sa.Column('question_weight', sa.Integer(), nullable=True))
    op.add_column('mc_responses', sa.Column('unacceptable_answers', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mc_responses', 'unacceptable_answers')
    op.drop_column('mc_responses', 'question_weight')
    # ### end Alembic commands ###
